services:
  - type: web
    name: hospital-backend
    env: node
    rootDir: hospital-backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: PORT
        value: 10000

  - type: static
    name: hospital-frontend
    rootDir: hospital-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free
